"""Phase 3: Add Draft and DraftSegment tables for Human-in-the-Loop

Revision ID: 3e4550d70470
Revises: 65bcd0335532
Create Date: 2026-01-02 11:59:04.609623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4550d70470'
down_revision: Union[str, Sequence[str], None] = '65bcd0335532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('content_plan_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EDITING', 'ASSETS_READY', 'CONVERTING', 'FINALIZED', name='draftstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_created_at'), 'drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_drafts_draft_id'), 'drafts', ['draft_id'], unique=True)
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.create_table('draft_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('image_search_query', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_local_path', sa.String(length=500), nullable=True),
    sa.Column('video_provider', sa.String(length=50), nullable=True),
    sa.Column('video_id', sa.String(length=100), nullable=True),
    sa.Column('tts_local_path', sa.String(length=500), nullable=True),
    sa.Column('tts_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_segments_draft_id'), 'draft_segments', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_segments_id'), 'draft_segments', ['id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_draft_segments_id'), table_name='draft_segments')
    op.drop_index(op.f('ix_draft_segments_draft_id'), table_name='draft_segments')
    op.drop_table('draft_segments')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_draft_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_created_at'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###
