"""Initial migration: Account, AccountSettings, JobHistory

Revision ID: 4c833fcf8fc7
Revises: 
Create Date: 2025-12-26 14:18:52.199674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c833fcf8fc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('credentials_path', sa.String(length=255), nullable=True),
    sa.Column('token_path', sa.String(length=255), nullable=True),
    sa.Column('channel_type', sa.Enum('HUMOR', 'TREND', 'INFO', 'REVIEW', 'NEWS', 'DAILY', name='channeltype'), nullable=True),
    sa.Column('default_prompt_style', sa.String(length=50), nullable=True),
    sa.Column('upload_schedule', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index(op.f('ix_accounts_channel_name'), 'accounts', ['channel_name'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tts_provider', sa.String(length=50), nullable=True),
    sa.Column('tts_voice_id', sa.String(length=100), nullable=True),
    sa.Column('tts_stability', sa.Float(), nullable=True),
    sa.Column('tts_similarity_boost', sa.Float(), nullable=True),
    sa.Column('tts_style', sa.Float(), nullable=True),
    sa.Column('default_format', sa.String(length=20), nullable=True),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('default_template', sa.String(length=50), nullable=True),
    sa.Column('bgm_enabled', sa.Boolean(), nullable=True),
    sa.Column('bgm_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_account_settings_id'), 'account_settings', ['id'], unique=False)
    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PLANNING', 'COLLECTING_ASSETS', 'EDITING', 'UPLOADING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('output_video_path', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_history_id'), 'job_history', ['id'], unique=False)
    op.create_index(op.f('ix_job_history_job_id'), 'job_history', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_history_job_id'), table_name='job_history')
    op.drop_index(op.f('ix_job_history_id'), table_name='job_history')
    op.drop_table('job_history')
    op.drop_index(op.f('ix_account_settings_id'), table_name='account_settings')
    op.drop_table('account_settings')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_channel_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
